### ISSUE TITLE
Unable install crawler.helper 

### ISSUE THREAD

**Issue by CR0405** [SimFin/pdf-crawler#11]
Hi Thomas Flassbeck ,

Could please help me to resolve this issue.
I'm unable to install   crawler.helper  package in pdf cawler.
<img width="872" alt="Crawler" src="https://user-images.githubusercontent.com/50352461/99385844-91052a00-28f7-11eb-9c3d-a8017f07f29a.PNG">

Thanks
Chinna R

**Comment by thf24** [comment]
Hi,
did you run the steps to install the package?

So in your terminal (the same folder your python file is in):
```
$ git clone https://github.com/SimFin/pdf-crawler.git
$ cd pdf-crawler

# Make a virtual environment with the tool of your choice. Please use Python version 3.6+
# Here an example based on pyenv:
$ pyenv virtualenv 3.6.6 pdf-crawler

$ pip install -e .
```

**Comment by CR0405** [comment]
Hi Thomas ,
It's working ,before I tried in spider so it was not worked.

Thank you 
Chinna R
